version: '3'
services:

  symfony-webapp:
    image: erighetto/drupal-dev:latest
    ports:
      - "8000:80"
    links:
      - pma
    volumes:
      - "./backend:/var/www/html:cached"
    environment:
      WEB_DOCUMENT_ROOT: "/var/www/html/public"
      PHP_IDE_CONFIG: "serverName=localhost"
      POSTFIX_RELAYHOST: "mailhog:1025"

  vue-webapp:
    image: node
    ports:
      - "8081:8081"
    working_dir: /home/node/app
    volumes:
      - "./frontend:/home/node/app"
    command: sh -c 'yarn run serve'

  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql-server
      PMA_USER: satgeorilievi_usr
      PMA_PASSWORD: satgeorilievi_pwd
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
    ports:
      - "8080:80"

  mysql-server:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD:  root
      MYSQL_DATABASE: satgeorilievi
      MYSQL_USER: satgeorilievi_usr
      MYSQL_PASSWORD: satgeorilievi_pwd
    ports:
      - "3306:3306"