satgeoroutes:
  home:
    title: 'Rilievi con laser scanner, rilievo celerimetrico, rilievi topografici, rilievi gps'
    description: 'Rilievo con laser scanner 3D, rilievi gps, rilievo celerimetrico, rilievi topografici'
    binding_path: 'home'
    menu: 'Home'
  chi-siamo:
    title: 'Chi siamo'
    description: 'La storia dello studio specialista in rilevazioni topografiche, rilevazione con gps e rilevazione con laser scanner 3D'
    binding_path: 'chi-siamo'
    menu: 'Chi siamo'
  servizi:
    title: 'Rilievo gps, rilievo laser scanner, rilievi topografici'
    description: 'Rilievo gps, rilievo laser scanner, rilievo celerimetrico e rilievo topografico per piani quotati, frazionamenti e tracciamenti, accatastamenti e riconfinazioni'
    binding_path: 'servizi'
    menu: 'Servizi'
  dove-siamo:
    title: 'Dove siamo'
    description: 'Dove siamo: Vestenanova, Verona, Veneto'
    binding_path: 'dove-siamo'
    menu: 'Dove siamo'
  contatti:
    title: 'Contatti'
    description: 'Contatti. Indirizzo mail. Vestenanova, Verona, Veneto'
    binding_path: 'contatti'
    menu: 'Contatti'