satgeoservices:
  rilievi-topografici:
      title: 'Rilievi con laser scanner, rilievo celerimetrico, rilievi topografici, rilievi gps'
      description: 'Rilievo con laser scanner 3D, rilievi gps, rilievo celerimetrico, rilievi topografici'
      binding_path: 'rilievi-topografici'
      menu: 'rilievo topografico'
      plural: 'rilievi topografici'
      image: 'rilievi-topografici-hover.jpg'
  piani-quotati:
      title: 'Rilievi con laser scanner, rilievo celerimetrico, rilievi topografici, rilievi gps'
      description: 'Rilievo con laser scanner 3D, rilievi gps, rilievo celerimetrico, rilievi topografici'
      binding_path: 'piani-quotati'
      menu: 'piano quotato'
      plural: 'piani quotati'
      image: 'piano-quotato-hover.jpg'
  frazionamenti-lottizzazioni:
      title: 'Rilievi con laser scanner, rilievo celerimetrico, rilievi topografici, rilievi gps'
      description: 'Rilievo con laser scanner 3D, rilievi gps, rilievo celerimetrico, rilievi topografici'
      binding_path: 'frazionamenti-lottizzazioni'
      menu: 'accatastamenti e riconfinazioni'
      plural: 'frazionamento e tracciamento'
      image: 'frazionamento-tracciamento-lottizzazione-hover.jpg'
  accatastamenti-riconfinazioni:
      title: 'Accatastamenti e riconfinazioni'
      description: 'Rilievi gps, rilievo celerimetrico, rilievi topografici per accatastamenti e riconfinazioni'
      binding_path: 'accatastamenti-riconfinazioni'
      menu: 'accatastamento e riconfinazione'
      plural: 'accatastamenti e riconfinazioni'
      image: 'accatastamento-riconfinazione-hover.jpg'
  progettazione-edile:
      title: 'Rilievi con laser scanner, rilievo celerimetrico, rilievi topografici, rilievi gps'
      description: 'Rilievo con laser scanner 3D, rilievi gps, rilievo celerimetrico, rilievi topografici'
      binding_path: 'progettazione-edile'
      menu: 'progettazione edile'
      plural: 'progettazione edile'
      image: 'progettazione-edile-hover.jpg'
